# Generated by Django 5.2.4 on 2025-08-15 04:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("study_buddy", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="interest",
            old_name="name",
            new_name="username",
        ),
        migrations.RenameField(
            model_name="student",
            old_name="name",
            new_name="username",
        ),
    ]
