# Generated by Django 5.2.4 on 2025-08-15 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("study_buddy", "0002_rename_name_interest_username_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="interest",
            old_name="username",
            new_name="name",
        ),
        migrations.AlterField(
            model_name="student",
            name="username",
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
