# Generated by Django 5.2.4 on 2025-08-15 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("study_buddy", "0003_rename_username_interest_name_alter_student_username"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="interest",
            name="name",
        ),
        migrations.AddField(
            model_name="interest",
            name="username",
            field=models.CharField(default="temp_user", max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name="student",
            name="username",
            field=models.CharField(default="temp_user", max_length=50, unique=True),
        ),
    ]
