# Generated by Django 5.2.4 on 2025-08-15 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("study_buddy", "0004_remove_interest_name_interest_username_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="interest",
            name="username",
        ),
        migrations.AddField(
            model_name="interest",
            name="name",
            field=models.CharField(default="no interest", max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name="student",
            name="username",
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
