# Generated by Django 5.2.4 on 2025-08-15 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("study_buddy", "0005_remove_interest_username_interest_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="interest",
            name="name",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="student",
            name="username",
            field=models.CharField(max_length=100),
        ),
    ]
